// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webApi.Data;

#nullable disable

namespace webApi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("webApi.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Product1",
                            Price = 10.0m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Product2",
                            Price = 20.0m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Product3",
                            Price = 30.0m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Product4",
                            Price = 40.0m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Product5",
                            Price = 50.0m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Product6",
                            Price = 60.0m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Product7",
                            Price = 70.0m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Product8",
                            Price = 80.0m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Product9",
                            Price = 90.0m
                        },
                        new
                        {
                            Id = 10,
                            Name = "Product10",
                            Price = 100.0m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
