// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webApi.Infrastructure.Data;

#nullable disable

namespace webApi.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250804014140_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("webApi.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Teclado",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Parlantes",
                            Price = 20.25m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Monitor",
                            Price = 30.30m
                        },
                        new
                        {
                            Id = 4,
                            Name = "USB",
                            Price = 40.25m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Laptop",
                            Price = 155.75m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mouse",
                            Price = 10.50m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Impresora",
                            Price = 99.99m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Webcam",
                            Price = 25.55m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Router",
                            Price = 45.77m
                        },
                        new
                        {
                            Id = 10,
                            Name = "Cargador",
                            Price = 15.88m
                        },
                        new
                        {
                            Id = 11,
                            Name = "Pendrive",
                            Price = 8.99m
                        },
                        new
                        {
                            Id = 12,
                            Name = "Disco Duro",
                            Price = 99.33m
                        },
                        new
                        {
                            Id = 13,
                            Name = "Tarjeta de Video",
                            Price = 250.75m
                        },
                        new
                        {
                            Id = 14,
                            Name = "Tarjeta Madre",
                            Price = 150.25m
                        },
                        new
                        {
                            Id = 15,
                            Name = "Fuente de Poder",
                            Price = 75.95m
                        },
                        new
                        {
                            Id = 16,
                            Name = "Memoria RAM",
                            Price = 60.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
