// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webApi.Infrastructure.Data;

#nullable disable

namespace webApi.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("webApi.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Teclado",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Parlantes",
                            Price = 20.25m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Monitor",
                            Price = 30.30m
                        },
                        new
                        {
                            Id = 4,
                            Name = "USB",
                            Price = 40.25m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Laptop",
                            Price = 155.75m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
